### ISSUE TITLE
--keep should be default

### ISSUE THREAD

**Issue by mirh** [mcmilk/zstdmt#11]

**Comment by jinfeihan57** [comment]
Can you describe the problem more clearly? I don't know what you mean.

**Comment by mirh** [comment]
At least when I decompress with zstd-mt-w64, on finishing the unpack the source file gets deleted (unless I use `-k`). 
That doesn't seem right as a default, especially if it even applied to compression.

**Comment by mcmilk** [comment]
I leave it as it is ... the behavior is taken from bzip2 / gzip.

**Comment by mirh** [comment]
..and?

**Comment by mcmilk** [comment]
AND: I leave it as it is ... the behavior is taken from bzip2 / gzip.
