### ISSUE TITLE
Any plan to support Linux platform? ( such as Debian, Arch, etc )

### ISSUE THREAD

**Issue by ottokang** [mcmilk/zstdmt#26]
As title.

**Comment by mcmilk** [comment]
I don't understand that question ;-)

Linux on any platform is supported ... e.g. just type `make` within the `programs` directory.

**Comment by ottokang** [comment]
Oh, I see the [Makefile](https://github.com/mcmilk/zstdmt/blob/master/programs/Makefile), THANKS
