### ISSUE TITLE
Unable to decompress with the original brotli？

### ISSUE THREAD

**Issue by Kingrd97** [mcmilk/zstdmt#30]
When I compress with brotli-mt, brotli-mt can decompress while brotli can not decompress
>brotli-mt test
>brotli -d -S brot test.brot
Corrupt input [test. brot]

**Comment by mcmilk** [comment]
Yes, I have added some additional headers for faster compressing / decompressing multiple chunks.
See [Brotli frame definition](https://github.com/mcmilk/zstdmt?tab=readme-ov-file#brotli-frame-definition).
