### ISSUE TITLE
Version information

### ISSUE THREAD

**Issue by tansy** [mcmilk/zstdmt#31]
Version information is somewhat confusing. It says: `zstd-mt version v1.5.5, zstdmt v0.8`, where 1.5.5 is in fact zstd version, and 0.8 is zstd-mt.
In my opinion it should be program version first, then libzstd version second. Perfectly in next line.

```
zstd-mt 0.8
libzstd 1.5.5

Copyright...
```
It's logical to display actual program version first, then its library.

Other program/s, using external library in same/similar way do it like that:

```
plzip 1.10
Using lzlib 1.14
Copyright...
```

Same would apply to the other programs from suite.

**Comment by mcmilk** [comment]
Yes, I will fix this ;)
