### ISSUE TITLE
snappy multithreading

### ISSUE THREAD

**Issue by jinfeihan57** [mcmilk/zstdmt#5]
Are there plans to add compression algorithms? I want to help. And I made snappy multithreading.

**Comment by mcmilk** [comment]
Not really, but if yu want snappy within zstdmt - no problem.
I would take some RP, I could also do some programming for that.... what do you mean with "And I made snappy multithreading." ?

**Comment by jinfeihan57** [comment]
RP？Do you mean PR ? I can submit PR.

**Comment by ipaucek4680** [comment]
@jinfeihan57 
You can explain "snappy multithreading" in Chinese and I will be happy to help you translate your words (comment) to English.
(你可以用中文解释 "snappy multithreading" 的意思。我乐意把你的留言翻译成英文。)

**Comment by jinfeihan57** [comment]
@ipaucek4680 snappy算法多线程
I'm working on it. It's will be finished this weekend.（我正在编写snappy的多线程，计划这周末完成。）

**Comment by ipaucek4680** [comment]
@mcmilk 
I believe he is referring to the compression library called "[Snappy](https://en.wikipedia.org/wiki/Snappy_(compression))".
He is working on implementing the multi-threading support of the Snappy library and would like to see if it can be merged into this repository. The work will be finished this weekend.

**Comment by jinfeihan57** [comment]
add snappy delete lz5 update zstd @mcmilk @ipaucek4680 
https://github.com/mcmilk/zstdmt/pull/7

**Comment by jinfeihan57** [comment]
add snappy delete lz5 update zstd @mcmilk @ipaucek4680
https://github.com/mcmilk/zstdmt/pull/7

**Comment by jinfeihan57** [comment]
add snappy delete lz5 update zstd @mcmilk @ipaucek4680
https://github.com/mcmilk/zstdmt/pull/7
https://github.com/jinfeihan57/zstdmt

**Comment by mcmilk** [comment]
@jinfeihan57 - yes, I meant pull request :-)

It's nice that you crated a PR, but please adjust the code C++ -> C ... And leave LZ5 there, but we may mark it obsolete - that would be nice I think.

**Comment by jinfeihan57** [comment]
I have restored lz5.

**Comment by mcmilk** [comment]
Thank, it's just there for reference ... and also 7-Zip ZS uses this lib, and a want to leave it there also.

**Comment by mcmilk** [comment]
Snappy is included now.

I will check the new code later, it was just merged without checks ;-)

**Comment by mcmilk** [comment]
I have rebased the commits today a bit ...  and moved the github tests into the Makefile
